# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/serban/work/github/gxna

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/serban/work/github/gxna

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/serban/work/github/gxna/CMakeFiles /Users/serban/work/github/gxna//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/serban/work/github/gxna/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gxna

# Build rule for target.
gxna: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gxna
.PHONY : gxna

# fast build rule for target.
gxna/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/build
.PHONY : gxna/fast

cpp/Args.o: cpp/Args.cpp.o
.PHONY : cpp/Args.o

# target to build an object file
cpp/Args.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Args.cpp.o
.PHONY : cpp/Args.cpp.o

cpp/Args.i: cpp/Args.cpp.i
.PHONY : cpp/Args.i

# target to preprocess a source file
cpp/Args.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Args.cpp.i
.PHONY : cpp/Args.cpp.i

cpp/Args.s: cpp/Args.cpp.s
.PHONY : cpp/Args.s

# target to generate assembly for a file
cpp/Args.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Args.cpp.s
.PHONY : cpp/Args.cpp.s

cpp/Distribution.o: cpp/Distribution.cpp.o
.PHONY : cpp/Distribution.o

# target to build an object file
cpp/Distribution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Distribution.cpp.o
.PHONY : cpp/Distribution.cpp.o

cpp/Distribution.i: cpp/Distribution.cpp.i
.PHONY : cpp/Distribution.i

# target to preprocess a source file
cpp/Distribution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Distribution.cpp.i
.PHONY : cpp/Distribution.cpp.i

cpp/Distribution.s: cpp/Distribution.cpp.s
.PHONY : cpp/Distribution.s

# target to generate assembly for a file
cpp/Distribution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Distribution.cpp.s
.PHONY : cpp/Distribution.cpp.s

cpp/Experiment.o: cpp/Experiment.cpp.o
.PHONY : cpp/Experiment.o

# target to build an object file
cpp/Experiment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Experiment.cpp.o
.PHONY : cpp/Experiment.cpp.o

cpp/Experiment.i: cpp/Experiment.cpp.i
.PHONY : cpp/Experiment.i

# target to preprocess a source file
cpp/Experiment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Experiment.cpp.i
.PHONY : cpp/Experiment.cpp.i

cpp/Experiment.s: cpp/Experiment.cpp.s
.PHONY : cpp/Experiment.s

# target to generate assembly for a file
cpp/Experiment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Experiment.cpp.s
.PHONY : cpp/Experiment.cpp.s

cpp/GeneNetwork.o: cpp/GeneNetwork.cpp.o
.PHONY : cpp/GeneNetwork.o

# target to build an object file
cpp/GeneNetwork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/GeneNetwork.cpp.o
.PHONY : cpp/GeneNetwork.cpp.o

cpp/GeneNetwork.i: cpp/GeneNetwork.cpp.i
.PHONY : cpp/GeneNetwork.i

# target to preprocess a source file
cpp/GeneNetwork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/GeneNetwork.cpp.i
.PHONY : cpp/GeneNetwork.cpp.i

cpp/GeneNetwork.s: cpp/GeneNetwork.cpp.s
.PHONY : cpp/GeneNetwork.s

# target to generate assembly for a file
cpp/GeneNetwork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/GeneNetwork.cpp.s
.PHONY : cpp/GeneNetwork.cpp.s

cpp/RandomPermutation.o: cpp/RandomPermutation.cpp.o
.PHONY : cpp/RandomPermutation.o

# target to build an object file
cpp/RandomPermutation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/RandomPermutation.cpp.o
.PHONY : cpp/RandomPermutation.cpp.o

cpp/RandomPermutation.i: cpp/RandomPermutation.cpp.i
.PHONY : cpp/RandomPermutation.i

# target to preprocess a source file
cpp/RandomPermutation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/RandomPermutation.cpp.i
.PHONY : cpp/RandomPermutation.cpp.i

cpp/RandomPermutation.s: cpp/RandomPermutation.cpp.s
.PHONY : cpp/RandomPermutation.s

# target to generate assembly for a file
cpp/RandomPermutation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/RandomPermutation.cpp.s
.PHONY : cpp/RandomPermutation.cpp.s

cpp/Statistics.o: cpp/Statistics.cpp.o
.PHONY : cpp/Statistics.o

# target to build an object file
cpp/Statistics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Statistics.cpp.o
.PHONY : cpp/Statistics.cpp.o

cpp/Statistics.i: cpp/Statistics.cpp.i
.PHONY : cpp/Statistics.i

# target to preprocess a source file
cpp/Statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Statistics.cpp.i
.PHONY : cpp/Statistics.cpp.i

cpp/Statistics.s: cpp/Statistics.cpp.s
.PHONY : cpp/Statistics.s

# target to generate assembly for a file
cpp/Statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/Statistics.cpp.s
.PHONY : cpp/Statistics.cpp.s

cpp/gxna.o: cpp/gxna.cpp.o
.PHONY : cpp/gxna.o

# target to build an object file
cpp/gxna.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/gxna.cpp.o
.PHONY : cpp/gxna.cpp.o

cpp/gxna.i: cpp/gxna.cpp.i
.PHONY : cpp/gxna.i

# target to preprocess a source file
cpp/gxna.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/gxna.cpp.i
.PHONY : cpp/gxna.cpp.i

cpp/gxna.s: cpp/gxna.cpp.s
.PHONY : cpp/gxna.s

# target to generate assembly for a file
cpp/gxna.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxna.dir/build.make CMakeFiles/gxna.dir/cpp/gxna.cpp.s
.PHONY : cpp/gxna.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gxna"
	@echo "... cpp/Args.o"
	@echo "... cpp/Args.i"
	@echo "... cpp/Args.s"
	@echo "... cpp/Distribution.o"
	@echo "... cpp/Distribution.i"
	@echo "... cpp/Distribution.s"
	@echo "... cpp/Experiment.o"
	@echo "... cpp/Experiment.i"
	@echo "... cpp/Experiment.s"
	@echo "... cpp/GeneNetwork.o"
	@echo "... cpp/GeneNetwork.i"
	@echo "... cpp/GeneNetwork.s"
	@echo "... cpp/RandomPermutation.o"
	@echo "... cpp/RandomPermutation.i"
	@echo "... cpp/RandomPermutation.s"
	@echo "... cpp/Statistics.o"
	@echo "... cpp/Statistics.i"
	@echo "... cpp/Statistics.s"
	@echo "... cpp/gxna.o"
	@echo "... cpp/gxna.i"
	@echo "... cpp/gxna.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

